QuanLySanBong/QuanLySanBong/Controllers/AccessController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using QuanLySanBong.Classes;
using QuanLySanBong.Data;
using QuanLySanBong.Models;

namespace QuanLySanBong.Controllers
{
    public class AccessController : Controller
    {
        private FootballContext db;
        public AccessController(FootballContext context)
        {
            db = context;
        }

        [HttpGet]      
        public ActionResult Login()
        {
                return View();           
        }

        [HttpPost]
        public ActionResult Login(String username, String password)
        {
            User user = db.User.FirstOrDefault(u => u.Username == username && u.Password == password);
            if (user != null)
            {
                ConstVar.User = user;
                return RedirectToAction("ListSanBong", "Home");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Register(User? user)
        {
            return View(user);
        }


        [HttpPost]
        public IActionResult CreateUser([FromForm] User user)
        {
            //if (db.User.Where(p => p.Username == user.Username).Count() > 0)
            //    ModelState.AddModelError("Username", "Đã tồn tại tên đăng nhập");
            //if (db.User.Where(p => p.PhoneNumber == user.PhoneNumber).Count() > 0)
            //    ModelState.AddModelError("PhoneNumber", "Số điện thoại đã được đăng ký");
            //if (!ModelState.IsValid)
            //{
            //    return View("Register", user);
            //}
            user.LoaiUser = false;
            db.User.Add(user);
            Cart cart = new Cart();
            cart.User = user;
            cart.Total = 0;
            db.Cart.Add(cart);
            db.SaveChanges();
            return RedirectToAction("Login");
        }

    }
}

QuanLySanBong/QuanLySanBong/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using QuanLySanBong.Classes;
using QuanLySanBong.Data;
using QuanLySanBong.Models;
using System.Security.Cryptography;
using System.Collections;
using System.Text.Json;
using System.IO;
using System.Runtime.Serialization.Formatters.Binary;

namespace QuanLySanBong.Controllers
{
    public class CartController : Controller
    {
        private FootballContext db;
        public CartController(FootballContext context)
        {
            db = context;
        }
        public IActionResult Cart()
        {
            ViewBag.Title = "Giỏ hàng";            
            var user = db.User.FirstOrDefault(u => u.UserId == ConstVar.User.UserId);
            if (user != null)
            {
                ViewBag.Name = user.DisplayName;
                ViewBag.userId = user.UserId;
            }
            var cartDetails = db.Cart.Include(p => p.CartDetails)
                         .ThenInclude(cd => cd.YardDetail)
                         .ThenInclude(yd => yd.PlayGround)
                         .Include(p => p.CartDetails)
                         .ThenInclude(cd => cd.YardDetail)
                         .ThenInclude(yd => yd.SubYard)
                         .Include(p => p.CartDetails)
                         .ThenInclude(cd => cd.YardDetail)
                         .ThenInclude(yd => yd.TimeSlot)
                         .FirstOrDefault(p => p.UserId == Classes.ConstVar.User.UserId)?.CartDetails
                         .ToList();
            var MyModelView = new Tuple<List<CartDetail>, User>(
                  cartDetails,
                  user
               );          
            return View(MyModelView);
        }
        public IActionResult Checkout()
        {
            return View();
        }

        public IActionResult CartChange(int cartDetailId)
        {
            var MyModelView = ListItemAfterDelete(ConstVar.User.UserId, cartDetailId);            
            return PartialView("BangCart", MyModelView);
        }

        public Tuple<List<CartDetail>, User> ListItemAfterDelete(int userId, int cartDetailId)
        {
            var user = db.User.FirstOrDefault(u => u.UserId == userId);
            if (user != null)
            {
                ViewBag.Name = user.DisplayName;
                ViewBag.userId = user.UserId;
            }

                var cartDetail = db.CartDetail.FirstOrDefault(cd => cd.CartDetailId == cartDetailId);
                if (cartDetail != null)
                {
                    db.CartDetail.Remove(cartDetail);
                    db.SaveChanges();
                }

                var cartDetails = db.Cart.Include(p => p.CartDetails)
                              .ThenInclude(cd => cd.YardDetail)
                              .ThenInclude(yd => yd.PlayGround)
                              .Include(p => p.CartDetails)
                              .ThenInclude(cd => cd.YardDetail)
                              .ThenInclude(yd => yd.SubYard)
                              .Include(p => p.CartDetails)
                              .ThenInclude(cd => cd.YardDetail)
                              .ThenInclude(yd => yd.TimeSlot)
                              .FirstOrDefault(p => p.UserId == user.UserId)?.CartDetails
                              .ToList();

            return new Tuple<List<CartDetail>, User>(
                  cartDetails,
                  user
               );
        }

        public IActionResult AddCartDetail()
        {
            int TongTien = 0;
            var cartDetails = db.Cart.Include(p => p.CartDetails)
                              .ThenInclude(cd => cd.YardDetail)
                              .ThenInclude(yd => yd.PlayGround)
                              .Include(p => p.CartDetails)
                              .ThenInclude(cd => cd.YardDetail)
                              .ThenInclude(yd => yd.SubYard)
                              .Include(p => p.CartDetails)
                              .ThenInclude(cd => cd.YardDetail)
                              .ThenInclude(yd => yd.TimeSlot)
                              .FirstOrDefault(p => p.UserId == ConstVar.User.UserId)?.CartDetails
                              .ToList();
            if (cartDetails.Count() == 0) return RedirectToAction("ListSanBong", "Home");
            Invoice invoice = new Invoice();
            invoice.UserId = ConstVar.User.UserId;
            invoice.DateCreate = DateTime.Now.Date;
            invoice.Total = 0;
            db.Invoice.Add(invoice);
            db.SaveChanges();

            int invoiceId = (int)db.Invoice.OrderByDescending(i => i.DateCreate).FirstOrDefault()?.InvoiceId;
            Invoice invoiceMS = db.Invoice.Find(invoiceId);

            foreach (var item in cartDetails)
            {
                InvoiceDetail invoiceDetail = new InvoiceDetail();
                invoiceDetail.InvoiceId = invoice.InvoiceId;
                invoiceDetail.YardDetailId = item.YardDetailId;
                invoiceDetail.DateBook = item.DateBook;
                invoiceDetail.Price = item.Price;
                db.InvoiceDetail.Add(invoiceDetail);
                db.CartDetail.Remove(item);
                TongTien += item.Price;
            }
            invoice.Total = TongTien;
            db.SaveChanges();
            return RedirectToAction("HoaDon", "Home", new { invoideId = invoice.InvoiceId });
        }       
    }
}

QuanLySanBong/QuanLySanBong/Views/Shared/Footer.cshtml
<footer class="footer py-4">
    <div class="container-fluid">
        <div class="row align-items-center justify-content-lg-between">
            <div class="col-lg-6 mb-lg-0 mb-4">
                <div class="copyright text-center text-sm text-muted text-lg-start">
                    © <script>
                          document.write(new Date().getFullYear())
                    </script>,
                    made with <i class="fa fa-heart"></i> by
                    <a href="https://www.creative-tim.com" class="font-weight-bold" target="_blank">Creative Tim</a>
                    for a better web.
                </div>
            </div>
            <div class="col-lg-6">
                <ul class="nav nav-footer justify-content-center justify-content-lg-end">
                    <li class="nav-item">
                        <a href="https://www.creative-tim.com" class="nav-link text-muted" target="_blank">Creative Tim</a>
                    </li>
                    <li class="nav-item">
                        <a href="https://www.creative-tim.com/presentation" class="nav-link text-muted" target="_blank">About Us</a>
                    </li>
                    <li class="nav-item">
                        <a href="https://www.creative-tim.com/blog" class="nav-link text-muted" target="_blank">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a href="https://www.creative-tim.com/license" class="nav-link pe-0 text-muted" target="_blank">License</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

QuanLySanBong/QuanLySanBong/Views/Shared/LayoutSanBong.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="../assets/img/favicon.png">
    <title>
        QUẢN LÝ SÂN BÓNG
    </title>
    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
    <!-- Nucleo Icons -->
    <link href="../assets/css/nucleo-icons.css" rel="stylesheet" />
    <link href="../assets/css/nucleo-svg.css" rel="stylesheet" />
    <!-- Font Awesome Icons -->
    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
    <!-- Material Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
    <!-- CSS Files -->
    <link id="pagestyle" href="../assets/css/material-dashboard.css?v=3.1.0" rel="stylesheet" />
    <!-- Nepcha Analytics (nepcha.com) -->
    <!-- Nepcha is a easy-to-use web analytics. No cookies and fully compliant with GDPR, CCPA and PECR. -->
    <script defer data-site="YOUR_DOMAIN_HERE" src="https://api.nepcha.com/js/nepcha-analytics.js"></script>
</head>

<body class="g-sidenav-show @Html.Raw(ViewBag.active ==  100? "bg-white":"bg-gray-200")">
    <!-- Begin Left menu -->
    <aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3   bg-gradient-dark" id="sidenav-main">
        <div id="layoutSidenav_nav">
            <partial name="LeftMenu" />
        </div>
    </aside>
    <!-- End Left menu -->
    <main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">
        <!-- Begin Top nav -->
        <partial name="TopNav" />
        <!-- End Top nav -->
        <div class="container-fluid py-4">
            <!-- Begin Main-->
            <main>
                @RenderBody()
            </main>
            <!-- End Main-->
            <!-- Begin Footer-->
            <partial name="Footer" />        
            <!-- End Footer-->
        </div>
    </main>
    <!--   Core JS Files   -->
    <script src="../assets/js/core/popper.min.js"></script>
    <script src="../assets/js/core/bootstrap.min.js"></script>
    <script src="../assets/js/plugins/perfect-scrollbar.min.js"></script>
    <script src="../assets/js/plugins/smooth-scrollbar.min.js"></script>
    <script src="../assets/js/plugins/chartjs.min.js"></script>
    <script>
        var ctx = document.getElementById("chart-bars").getContext("2d");

        new Chart(ctx, {
            type: "bar",
            data: {
                labels: ["M", "T", "W", "T", "F", "S", "S"],
                datasets: [{
                    label: "Sales",
                    tension: 0.4,
                    borderWidth: 0,
                    borderRadius: 4,
                    borderSkipped: false,
                    backgroundColor: "rgba(255, 255, 255, .8)",
                    data: [50, 20, 10, 22, 50, 10, 40],
                    maxBarThickness: 6
                },],
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                    legend: {
                        display: false,
                    }
                },
                interaction: {
                    intersect: false,
                    mode: 'index',
                },
                scales: {
                    y: {
                        grid: {
                            drawBorder: false,
                            display: true,
                            drawOnChartArea: true,
                            drawTicks: false,
                            borderDash: [5, 5],
                            color: 'rgba(255, 255, 255, .2)'
                        },
                        ticks: {
                            suggestedMin: 0,
                            suggestedMax: 500,
                            beginAtZero: true,
                            padding: 10,
                            font: {
                                size: 14,
                                weight: 300,
                                family: "Roboto",
                                style: 'normal',
                                lineHeight: 2
                            },
                            color: "#fff"
                        },
                    },
                    x: {
                        grid: {
                            drawBorder: false,
                            display: true,
                            drawOnChartArea: true,
                            drawTicks: false,
                            borderDash: [5, 5],
                            color: 'rgba(255, 255, 255, .2)'
                        },
                        ticks: {
                            display: true,
                            color: '#f8f9fa',
                            padding: 10,
                            font: {
                                size: 14,
                                weight: 300,
                                family: "Roboto",
                                style: 'normal',
                                lineHeight: 2
                            },
                        }
                    },
                },
            },
        });


        var ctx2 = document.getElementById("chart-line").getContext("2d");

        new Chart(ctx2, {
            type: "line",
            data: {
                labels: ["Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
                datasets: [{
                    label: "Mobile apps",
                    tension: 0,
                    borderWidth: 0,
                    pointRadius: 5,
                    pointBackgroundColor: "rgba(255, 255, 255, .8)",
                    pointBorderColor: "transparent",
                    borderColor: "rgba(255, 255, 255, .8)",
                    borderColor: "rgba(255, 255, 255, .8)",
                    borderWidth: 4,
                    backgroundColor: "transparent",
                    fill: true,
                    data: [50, 40, 300, 320, 500, 350, 200, 230, 500],
                    maxBarThickness: 6

                }],
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                    legend: {
                        display: false,
                    }
                },
                interaction: {
                    intersect: false,
                    mode: 'index',
                },
                scales: {
                    y: {
                        grid: {
                            drawBorder: false,
                            display: true,
                            drawOnChartArea: true,
                            drawTicks: false,
                            borderDash: [5, 5],
                            color: 'rgba(255, 255, 255, .2)'
                        },
                        ticks: {
                            display: true,
                            color: '#f8f9fa',
                            padding: 10,
                            font: {
                                size: 14,
                                weight: 300,
                                family: "Roboto",
                                style: 'normal',
                                lineHeight: 2
                            },
                        }
                    },
                    x: {
                        grid: {
                            drawBorder: false,
                            display: false,
                            drawOnChartArea: false,
                            drawTicks: false,
                            borderDash: [5, 5]
                        },
                        ticks: {
                            display: true,
                            color: '#f8f9fa',
                            padding: 10,
                            font: {
                                size: 14,
                                weight: 300,
                                family: "Roboto",
                                style: 'normal',
                                lineHeight: 2
                            },
                        }
                    },
                },
            },
        });

        var ctx3 = document.getElementById("chart-line-tasks").getContext("2d");

        new Chart(ctx3, {
            type: "line",
            data: {
                labels: ["Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
                datasets: [{
                    label: "Mobile apps",
                    tension: 0,
                    borderWidth: 0,
                    pointRadius: 5,
                    pointBackgroundColor: "rgba(255, 255, 255, .8)",
                    pointBorderColor: "transparent",
                    borderColor: "rgba(255, 255, 255, .8)",
                    borderWidth: 4,
                    backgroundColor: "transparent",
                    fill: true,
                    data: [50, 40, 300, 220, 500, 250, 400, 230, 500],
                    maxBarThickness: 6

                }],
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                    legend: {
                        display: false,
                    }
                },
                interaction: {
                    intersect: false,
                    mode: 'index',
                },
                scales: {
                    y: {
                        grid: {
                            drawBorder: false,
                            display: true,
                            drawOnChartArea: true,
                            drawTicks: false,
                            borderDash: [5, 5],
                            color: 'rgba(255, 255, 255, .2)'
                        },
                        ticks: {
                            display: true,
                            padding: 10,
                            color: '#f8f9fa',
                            font: {
                                size: 14,
                                weight: 300,
                                family: "Roboto",
                                style: 'normal',
                                lineHeight: 2
                            },
                        }
                    },
                    x: {
                        grid: {
                            drawBorder: false,
                            display: false,
                            drawOnChartArea: false,
                            drawTicks: false,
                            borderDash: [5, 5]
                        },
                        ticks: {
                            display: true,
                            color: '#f8f9fa',
                            padding: 10,
                            font: {
                                size: 14,
                                weight: 300,
                                family: "Roboto",
                                style: 'normal',
                                lineHeight: 2
                            },
                        }
                    },
                },
            },
        });
    </script>
    <script>
        var win = navigator.platform.indexOf('Win') > -1;
        if (win && document.querySelector('#sidenav-scrollbar')) {
            var options = {
                damping: '0.5'
            }
            Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
        }
    </script>
    <!-- Github buttons -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
    <script src="../assets/js/material-dashboard.min.js?v=3.1.0"></script>
    <!-- File jquery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    @RenderSection("Scripts", required:false)
</body>

</html>

QuanLySanBong/QuanLySanBong/Views/Shared/LeftMenu.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3   bg-gradient-dark" id="sidenav-main">
    <div class="sidenav-header">
        <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
        <a class="navbar-brand m-0" asp-controller="Home" asp-action = "ListSanBong" target="_blank">
            <img src="../assets/img/logo-ct.png" class="navbar-brand-img h-100" alt="main_logo">
            <span class="ms-1 font-weight-bold text-white">QUẢN LÝ SÂN BÓNG</span>
        </a>
    </div>
    <hr class="horizontal light mt-0 mb-2">
    <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link text-white @Html.Raw(ViewBag.active == 1 ? "active bg-gradient-primary":"")" asp-controller="Home" asp-action="ListSanBong">
                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="material-icons opacity-10">dashboard</i>
                    </div>
                    <span class="nav-link-text ms-1">Danh sách sân bóng</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white @Html.Raw(ViewBag.active == 2 ? "active bg-gradient-primary":"")" asp-controller="Home" asp-action="SanDaDat">
                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="material-icons opacity-10">table_view</i>
                    </div>
                    <span class="nav-link-text ms-1">Sân đã đặt</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white @Html.Raw(ViewBag.active == 3 ? "active bg-gradient-primary":"")" asp-controller="Home" asp-action="HoaDon" >
                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="material-icons opacity-10">receipt_long</i>
                    </div>
                    <span class="nav-link-text ms-1">Hóa đơn</span>
                </a>
            </li>                   
            <li class="nav-item mt-3">
                <h6 class="ps-4 ms-2 text-uppercase text-xs text-white font-weight-bolder opacity-8">Account pages</h6>
            </li>          
            <li class="nav-item">
                <a class="nav-link text-white " asp-controller="Access" asp-action="Login">
                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="material-icons opacity-10">logout</i>
                    </div>
                    <span class="nav-link-text ms-1">Đăng xuất</span>
                </a>
            </li>
        </ul>
    </div>
</aside>

QuanLySanBong/QuanLySanBong/Views/Shared/TopNav.cshtml
<nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" data-scroll="true">
    <div class="container-fluid py-1 px-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
                <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="javascript:;">Pages</a></li>
                <li class="breadcrumb-item text-sm text-dark active" aria-current="page">@ViewBag.Title</li>
            </ol>
            <h6 class="font-weight-bolder mb-0">@ViewBag.Title</h6>
        </nav>
        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
            <div class="ms-md-auto pe-md-3 d-flex align-items-center">
                <div class="input-group input-group-outline">
                    <label class="form-label">Tìm theo địa chỉ,tên sân</label>
                    <input type="text" class="form-control" id="search-input">
                </div>
            </div>
            <ul class="navbar-nav  justify-content-end">
                <li class="nav-item d-xl-none ps-3 d-flex align-items-center">
                    <a href="javascript:;" class="nav-link text-body p-0 me-sm-4" id="iconNavbarSidenav">
                        <div class="sidenav-toggler-inner">
                            <i class="sidenav-toggler-line"></i>
                            <i class="sidenav-toggler-line"></i>
                            <i class="sidenav-toggler-line"></i>
                        </div>
                    </a>
                </li>
                <li class="nav-item d-flex align-items-center">
                    <a asp-controller="Cart" asp-action="Cart" class="nav-link text-body font-weight-bold px-0 cart-icon me-sm-4">
                        <i class="fas fa-shopping-cart"></i>
                        <span class="cart-count">@ViewBag.Quantity</span>
                    </a>
                </li>
                <li class="nav-item d-flex align-items-center">
                    <a href="#" class="nav-link text-body font-weight-bold px-0">
                        <i class="fa fa-user me-sm-1"></i>
                        <a class="d-sm-inline d-none" >@ViewBag.Name</a>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<style>
    .cart-icon {
        position: relative;
        display: inline-block;
    }

    .cart-count {
        position: absolute;
        top: -5px;
        right: -12px;
        background-color: red;
        color: white;
        font-size: 11px;
        padding: 2px 6px;
        border-radius: 50%;
    }
</style>
<script>
    var searchInput = document.getElementById('search-input');
    searchInput.addEventListener('keydown', function (event) {
        if (event.key === 'Enter') {
            const searchText = searchInput.value;
            const url = '/Home/ListSanBong?searchInput=' + encodeURIComponent(searchText);
            window.location.href = url;
        }
    });
</script>

QuanLySanBong/QuanLySanBong/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QuanLySanBong</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/QuanLySanBong.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="ListSanBong">QuanLySanBong</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ListSanBong">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - QuanLySanBong - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>